exports.palletes = [
  [{ name: 'Chocolate Sunset', colors: ['#BF8777', '#7F5A4F', '#FFB49E', '#402D28', '#E5A28F'] }],
  [{ name: 'Angry Blossom', colors: ['#6FBF83', '#4A7F58', '#93FFAF', '#25402C', '#85E59E'] }],
  [{ name: 'Coffee Addiction', colors: ['#BF7859', '#7F503B', '#FFA077', '#40281E', '#E5906B'] }],
  [{ name: 'I Feel Blue', colors: ['#5CAABF', '#3D717F', '#7BE3FF', '#1F3940', '#6ECCE5'] }],
  [{ name: 'Love', colors: ['#BF5F5D', '#7F3F3E', '#FF7E7D', '#592C2B', '#E57170'] }],
  [{ name: 'Discord a e s t h e t i c s', colors: ['#9890BF', '#65607F', '#CBC0FF', '#333040', '#B7ADE5'] }],
  [{ name: 'Clouds', colors: ['#34BFAB', '#237F72', '#45FFE4', '#114039', '#3EE5CD'] }],
  [{ name: 'Bubblegum', colors: ['#BF7FA4', '#7F546D', '#FFA9DA', '#402A37', '#E598C4'] }],
  [{ name: 'Fake Love', colors: ['#A28EBF', '#6C5F7F', '#D8BDFF', '#362F40', '#C3AAE5'] }],
  [{ name: 'Reciprocal', colors: ['#BF635B', '#7F423D', '#FF847A', '#592E2B', '#E5776E'] }],
  [{ name: 'Chill', colors: ['#BFB293', '#7F7762', '#FFEEC5', '#403B31', '#E5D6B1'] }],
  [{ name: 'Pills', colors: ['#8576BF', '#594F7F', '#B29DFF', '#3E3759', '#A08DE5'] }],
  [{ name: 'Honeycomb', colors: ['#BF5C36', '#7F3D24', '#FF7B48', '#401F12', '#E56F41'] }],
  [{ name: 'Sweet Friendzone', colors: ['#BF3876', '#7F254E', '#FF4B9D', '#401327', '#E5438D'] }],
  [{ name: 'Marina', colors: ['#11AABF', '#0B717F', '#17E2FF', '#063940', '#14CCE5'] }],
  [{ name: 'Summer', colors: ['#BF5F44', '#7F3F2D', '#FF7E5B', '#402017', '#E57152'] }],
  [{ name: 'February', colors: ['#BF833C', '#7F5728', '#FFAE50', '#402C14', '#E59D48'] }],
  [{ name: 'Garden', colors: ['#4ABF4D', '#317F34', '#62FF67', '#19401A', '#58E55D'] }],
  [{ name: 'Hope', colors: ['#BBBDBF', '#7D7E7F', '#FAFCFF', '#3E3F40', '#E1E3E5'] }],
  [{ name: 'April Love', colors: ['#BF6283', '#7F4258', '#FF83AF', '#40212C', '#E5769E'] }],
  [{ name: 'Numb', colors: ['#BFAD8B', '#7F745C', '#FFE7B9', '#403A2E', '#E5D0A6'] }],
  [{ name: 'Harmony', colors: ['#68B298', '#CAFFEC', '#B0FFE3', '#B26958', '#FFBFB0'] }],
  [{ name: 'Childhood', colors: ['#B26E68', '#FFCECA', '#FFB6B0', '#58B27E', '#78FFB1'] }],
];

exports.cuteCatMessages = [
  'a cute kitty for you!',
  'so cuteeeeeee!!!!',
  'a ~~bunny~~ cat for u!',
  'it\'s so cute, don\'t you think?',
  'ALL HUMANS SHOULD OBEY THE CAT LORD... ugh, what happened?',
  'one, two, three cute cats!',
  'here kittennn',
  'I love cats!',
  'I already told you that I love cats?',
  'nobody is ever tired of cute cat gifs',
];

exports.reactionTexts = {
  alone: {
    idc: 'dun care...',
    angry: 'is angryyyy!!',
    positive: 'is feeling positive!! uwu',
    ew: ': ewwwwww.',
  },
};

exports.gifs = {
  hugs: [
    'https://i.imgur.com/r9aU2xv.gif',
    'https://i.imgur.com/wOmoeF8.gif',
    'https://i.imgur.com/nrdYNtL.gif',
    'https://i.imgur.com/BPLqSJC.gif',
    'https://i.imgur.com/ntqYLGl.gif',
    'https://i.imgur.com/v47M1S4.gif',
    'https://i.imgur.com/82xVqUg.gif',
    'https://i.imgur.com/4oLIrwj.gif',
    'https://i.imgur.com/6qYOUQF.gif',
    'https://i.imgur.com/UMm95sV.gif',
    'https://i.imgur.com/QJbBsDJ.gif',
    'https://i.imgur.com/tH9ras2.gif',
    'https://i.imgur.com/5Fowm1T.gif',
    'https://i.imgur.com/yLLtIQ1.gif',
    'https://i.imgur.com/WIrSZI6.gif',
    'https://i.imgur.com/wxN8TPQ.gif',
    'https://i.imgur.com/sqPf4dy.gif',
    'https://i.imgur.com/mtqQ86A.gif',
    'http://i.imgur.com/xfKmxEv.gif',
    'https://i.imgur.com/5UXmsH6.gif',
  ],
  idc: [
    'https://i.imgur.com/FVJovCq.gif',
    'https://i.imgur.com/8UlS2RT.gif',
    'https://i.imgur.com/7KnwjKP.gif',
    'https://i.imgur.com/thWQIzb.gif',
    'https://i.imgur.com/ToVmSUO.gif',
    'https://i.imgur.com/PMwmNk8.gif',
    'https://i.imgur.com/LzEtyfi.gif',
  ],
  angry: [
    'https://i.imgur.com/M3BG3Ck.gif',
    'https://i.imgur.com/vfYuufN.gif',
    'https://i.imgur.com/lYhZlzP.gif',
    'https://i.imgur.com/dnC7bRI.gif',
    'https://i.imgur.com/xonwJUs.gif',
    'https://i.imgur.com/CHUms5D.gif',
    'https://i.imgur.com/NWR9bSm.gif',
    'https://i.imgur.com/YFzdMLQ.gif',
    'https://i.imgur.com/1xyu51U.gif',
    'https://i.imgur.com/xCuy53l.gif',
  ],
  positive: [
    'https://i.imgur.com/T448KBj.gif',
    'https://i.imgur.com/DVLbS8o.gif',
    'https://i.imgur.com/ZcGTvrg.gif',
    'https://i.imgur.com/PH6RID7.gif',
    'https://i.imgur.com/yNRHB0h.gif',
    'https://i.imgur.com/qSNb4Ob.gif',
    'https://i.imgur.com/L4XFGoU.gif',
    'http://i.imgur.com/eCTPrKL.gif',
  ],
  charm: [
    'https://i.imgur.com/CPYxQIk.gif',
    'https://i.imgur.com/RlFg4qT.gif',
    'https://i.imgur.com/Ci5fOW7.gif',
    'https://i.imgur.com/KnBvOge.gif',
  ],
  poke: [
    'https://i.imgur.com/C98QBIH.gif',
  ],
  ew: [
    'https://78.media.tumblr.com/ae8ccc3a6fcbd1cf8a9904e840aa9ee4/tumblr_inline_njoj09Dg571tnaiq6.gif',
  ],
  yummy: [
    'https://i.imgur.com/46zKpo8.gif',
    'https://i.imgur.com/Sb2Eowc.gif',
  ],
};
